# Read files "100.jpeg" through "199.jpeg" into an NTSC clip
#ImageSource("C:\Documents and Settings\hari\My Documents\My Pictures\3DCapturing\3D Output\IndependentJPEG\Stereo%04d_l.jpg", 1, 746, 15.00)
ImageSource("\ImagesCamera2_backup\Snap%01d*.tiff", 1, 9, 3.00)
ImageSource("\ImagesCamera2_backup\Snap%02d*.tiff", 10, 99, 3.00)
ImageSource("\ImagesCamera2_backup\Snap%03d*.tiff", 100, 999, 3.00)
ImageSource("\ImagesCamera2_backup\Snap%04d*.tiff", 1000, 9999, 3.00)
ImageSource("\ImagesCamera2_backup\Snap%05d*.tiff", 10000, 99999, 3.00)
ImageSource("\ImagesCamera2_backup\Snap%06d*.tiff", 100000, 999999, 3.00)